# Generated by Django 4.2.6 on 2023-10-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastnotification',
            options={},
        ),
        migrations.RemoveField(
            model_name='broadcastnotification',
            name='broadcast_on',
        ),
    ]
